import json
from pathlib import Path

D = {
"test": ("un diapason et une règle graduée sur fond neutre", "schéma technique minimaliste au trait fin", "gris clair, blanc, un accent bleu", "sans empattement mince, style technique"),
"auto": ("dix pastilles de couleurs différentes disposées en cercle", "aplats géométriques pop", "arc-en-ciel vif sur fond sombre", "sans empattement géométrique gras"),
"perso": ("une plume et une feuille de papier à lettres", "aquarelle douce", "rose poudré, ocre, crème", "écriture manuscrite élégante"),
"francais_tests-electro": ("une plume qui se transforme en ondes lumineuses", "néon synthwave", "magenta, cyan, noir", "sans empattement fin futuriste"),
"francais_tests-folk": ("une plume posée sur une guitare acoustique et des feuilles", "gravure sur bois colorée", "brun, vert mousse, crème", "serif rustique"),
"francais_tests-rock": ("une plume enflammée devant un ampli", "affiche de concert sérigraphiée", "rouge, noir, jaune", "sans empattement condensé gras"),
"francais_tests-classique": ("une plume et une partition ancienne", "gravure dorée sur papier ancien", "bordeaux, or, ivoire", "serif classique à empattements fins"),
"francais_tests-gregorien": ("un parchemin avec neumes et lettrine enluminée", "enluminure médiévale", "or, bleu lapis-lazuli, rouge sombre", "onciale gothique"),
"francais_tests-chorale": ("des silhouettes de choristes en demi-cercle sous une lumière chaude", "illustration lumineuse douce", "or chaud, bordeaux, bleu nuit", "serif humaniste"),
"instrumental": ("un piano, un violoncelle et une ligne d'horizon cinématographique", "composition de film minimaliste", "bleu acier, gris, orange crépuscule", "sans empattement large espacé"),
"disco-en": ("une boule à facettes et un sol lumineux en damier", "illustration disco années 70", "rose, violet, or", "arrondie rétro années 70"),
"groove-en": ("des mains qui claquent et un micro vintage", "pop art à demi-teintes", "orange, brun chocolat, jaune moutarde", "grasse arrondie funk"),
"electro-atmospherique": ("un piano dans la brume au-dessus d'une ville", "photographie floue éthérée", "bleu gris, mauve, argent", "sans empattement fin très espacé"),
"electro-pop-fr": ("des bulles de lumière et un synthétiseur coloré", "pop acidulé", "corail, turquoise, jaune pâle", "arrondie ludique"),
"annees-50": ("un juke-box et un disque vinyle sur fond de diner américain", "affiche publicitaire rétro", "rouge cerise, turquoise, crème", "script rétro années 50"),
"futuriste-2046": ("une ville flottante avec des panneaux holographiques", "rendu futuriste épuré", "blanc, cyan, violet électrique", "sans empattement futuriste géométrique"),
"poesie-fr": ("une plume, un encrier et une fenêtre sur les toits de Paris", "lavis d'encre", "sépia, gris perle, bleu de Prusse", "serif littéraire classique"),
"poesie-en": ("un livre ouvert dans une lande brumeuse", "peinture romantique", "vert sombre, gris-bleu, or pâle", "serif anglais italique"),
"percussion-amerique-sud": ("des tambours colorés et des motifs de carnaval", "papier découpé coloré", "vert, jaune, bleu, rouge vifs", "grasse festive"),
"percussion-afrique": ("des djembés et un soleil couchant sur la savane", "motifs textiles africains en aplats", "terre cuite, ocre, indigo", "grasse aux angles taillés"),
"rap-fr-melodique": ("un casque, un micro et des néons de ville la nuit", "illustration urbaine sombre", "violet, bleu nuit, rose fluo", "sans empattement épais type affiche urbaine"),
"tribal": ("un feu de camp et des masques rituels", "peinture rupestre stylisée", "rouge ocre, noir, blanc cassé", "lettres taillées brutes"),
"acappella-hommes": ("des silhouettes d'hommes en cercle près d'un port", "gravure marine à l'encre", "bleu marine, sable, blanc", "serif gras marin"),
"acappella-femmes": ("des silhouettes de femmes dans un jardin fleuri", "aquarelle florale", "lilas, vert tendre, rose", "script délicat"),
"guitare-seule": ("une guitare acoustique seule sous un faisceau de lumière", "dessin au fusain", "noir, gris, un reflet doré", "sans empattement fin manuscrit"),
"harpe-seule": ("une harpe dorée dans une forêt de brume", "illustration féerique", "or, vert émeraude, bleu pâle", "serif ornemental fin"),
"piano-seul": ("un piano à queue vu du dessus et des touches", "noir et blanc contrasté", "noir, blanc, un accent rouge", "serif didone élégant"),
"chant-mongol": ("une yourte et un cavalier dans la steppe immense", "peinture de paysage large", "bleu ciel, vert steppe, ocre", "sans empattement aux traits calligraphiques"),
"electro-spatiale": ("des synthétiseurs analogiques vintage sous un ciel étoilé", "isométrique lumineux", "bleu nuit, bleu électrique", "serif italique"),
"synthes-epiques": ("une planète géante et un vaisseau face à un lever de soleil", "illustration cinématographique épique", "orange, violet profond, noir", "serif gravé de cinéma"),
"rock-progressif-instrumental": ("un paysage onirique avec des îles flottantes", "illustration surréaliste de pochette progressive", "turquoise, violet, orange", "serif fantastique"),
"funk-saxophone": ("un saxophone doré et des notes qui s'envolent", "illustration pop rétro", "or, orange, brun", "grasse funky arrondie"),
"tech": ("des formes géométriques épurées et une grille", "design suisse minimaliste", "blanc, noir, orange vif", "sans empattement grotesque"),
"hard-tech": ("un entrepôt industriel, lasers et fumée", "photographie contrastée sombre", "noir, rouge, blanc strobo", "sans empattement ultra condensé"),
"jeux-video": ("un héros en pixels devant un paysage de niveau", "pixel art 16 bits", "couleurs saturées de console, ciel bleu", "police pixel 8 bits"),
"hard-rock": ("une guitare électrique en flammes et des éclairs", "illustration de pochette hard rock", "noir, rouge, chrome", "lettres métalliques anguleuses"),
"disco-es": ("une boule à facettes sous un ciel de Madrid au crépuscule", "illustration disco chaude", "rouge, orange, rose", "arrondie rétro"),
"disco-pt": ("une boule à facettes devant la baie de Lisbonne et des azulejos", "illustration disco avec motifs d'azulejos", "bleu azulejo, blanc, jaune", "arrondie rétro"),
"disco-it": ("une boule à facettes et une vespa sur une place italienne", "illustration pop méditerranéenne", "vert, blanc, rouge, or", "arrondie rétro élégante"),
"disco-de": ("une boule à facettes et un tramway de Berlin la nuit", "collage graphique néon", "noir, jaune, magenta", "sans empattement bauhaus"),
"flamenco": ("une danseuse en robe rouge et une guitare", "peinture à l'huile gestuelle", "rouge, noir, or", "script calligraphique ample"),
"tango": ("un couple de danseurs sous un lampadaire à Buenos Aires", "illustration noir et blanc avec accent rouge", "noir, blanc, rouge sang", "serif art déco"),
"reggae-dub": ("un lion et un soleil sur fond de montagnes tropicales", "peinture murale colorée", "vert, jaune, rouge", "grasse arrondie reggae"),
"afrobeats": ("une rue animée de Lagos avec des tissus wax", "collage de motifs wax", "orange, turquoise, jaune, rose", "grasse géométrique"),
"maghreb": ("un oud et des arabesques de zellige", "mosaïque de zelliges", "bleu majorelle, blanc, terre cuite", "calligraphie géométrique stylisée"),
"klezmer": ("une clarinette et un violon sur un toit de village", "peinture naïve façon Chagall", "bleu, vert, rouge, jaune doux", "serif manuscrit"),
"balkans": ("une fanfare dans un village de montagne", "gravure populaire colorée", "rouge, or, vert", "serif gras folklorique"),
"celtique": ("des pierres dressées et un noeud celtique", "enluminure et entrelacs", "vert, or, gris pierre", "onciale celtique"),
"nordique": ("un fjord, une nyckelharpa et des runes", "gravure scandinave épurée", "bleu glacier, blanc, rouge brique", "lettres runiques stylisées"),
"gamelan": ("un orchestre de gamelan et un temple de Java", "batik coloré", "or, brun, indigo", "serif orné d'inspiration javanaise"),
"inde-classique": ("un sitar, un lotus et un mandala", "miniature indienne", "safran, rouge, or", "lettres calligraphiques ornées"),
"bollywood": ("une danseuse en saris colorés et des décors de cinéma", "affiche de film peinte à la main", "rose vif, jaune, bleu", "grasse affiche de cinéma"),
"japon-traditionnel": ("un koto, des cerisiers et le mont Fuji", "estampe ukiyo-e", "indigo, rose pâle, blanc", "pinceau calligraphique"),
"chine-traditionnelle": ("un guzheng, des montagnes brumeuses et un pont", "peinture à l'encre chinoise", "noir d'encre, vermillon, blanc", "pinceau calligraphique"),
"polynesie": ("un ukulélé, une plage et des fleurs d'hibiscus", "illustration tropicale", "turquoise, corail, vert", "script ludique"),
"mariachi": ("un trompettiste en costume brodé et des papel picado", "illustration folklorique colorée", "rouge, vert, or, rose", "grasse ornée"),
"salsa-latine": ("des danseurs et des percussions dans la rue de La Havane", "affiche tropicale vitaminée", "orange, magenta, turquoise", "grasse dynamique italique"),
"bachata-merengue": ("une guitare et des bongos sur une terrasse des Caraïbes", "illustration chaude romantique", "rose, doré, bleu profond", "script romantique"),
"bresil": ("la plage de Rio, un cavaquinho et des feuilles tropicales", "illustration tropicale moderniste", "vert, jaune, bleu", "grasse arrondie"),
"caraibes": ("des steel drums sur une plage au coucher de soleil", "aquarelle tropicale", "turquoise, orange, rose", "script ludique"),
"gospel": ("un orgue d'église et des rayons de lumière dans les vitraux", "vitrail lumineux", "bleu, rouge, or", "serif chaleureux"),
"blues": ("une guitare électrique et un harmonica sur un porche du Delta", "photographie sépia granuleuse", "sépia, brun, bleu usé", "lettres de pochette vintage"),
"jazz-varie": ("un saxophone, une contrebasse et la fumée d'un club", "illustration style Blue Note", "bleu, noir, blanc", "sans empattement type Blue Note"),
"soul-motown": ("un tambourin et une scène de théâtre des années 60", "illustration pop années 60", "jaune, bleu, rouge, blanc", "sans empattement rond années 60"),
"hip-hop-beats": ("des platines, un sampler et des disques", "collage street art", "jaune, noir, rouge", "lettres de tag graffiti lisibles"),
"drum-and-bass": ("une onde sonore violente et une ville de nuit", "glitch graphique", "vert acide, noir, violet", "sans empattement étroit glitch"),
"house-trance": ("une foule qui danse sous des faisceaux de lumière", "illustration énergique", "bleu électrique, violet, rose", "sans empattement futuriste italique"),
"ambient-chill": ("une pièce cosy avec une lampe et la pluie sur la fenêtre", "illustration lo-fi douce", "violet doux, beige, bleu nuit", "script fin"),
"metal": ("un crâne, des montagnes sombres et des éclairs", "illustration gravée sombre", "noir, gris acier, rouge sang", "gothique anguleux"),
"punk-indie": ("un collage de coupures de journaux et une guitare", "collage photocopié", "noir, blanc, rose fluo", "lettres découpées style rançon"),
"classique-varie": ("un orchestre dans une salle de concert dorée", "peinture classique", "or, rouge velours, noir", "serif classique élégant"),
"country-bluegrass": ("un banjo, un violon et une grange au soleil couchant", "illustration d'affiche americana", "brun, orange, bleu délavé", "slab serif western"),
"ska-rocksteady": ("un damier noir et blanc, une trompette et un chapeau", "graphisme two-tone", "noir, blanc, rouge", "sans empattement style two-tone"),
"valse-musette": ("un bal populaire sous des guirlandes et un accordéon", "affiche française des années 30", "rouge, crème, bleu", "script rétro parisien"),
"medieval-renaissance": ("un luth, un château et des étendards", "tapisserie médiévale", "rouge, or, vert profond", "gothique lisible"),
"esprit-dylan": ("une silhouette avec harmonica et guitare sur une route poussiéreuse", "dessin au trait granuleux en noir et blanc", "noir, blanc cassé, jaune moutarde", "sans empattement manuscrit des années 60"),
"esprit-jackson": ("des gants et une scène éclairée avec des projecteurs", "illustration pop brillante années 80", "noir, or, blanc, rouge", "sans empattement pop années 80"),
"esprit-hallyday": ("une moto, un micro et un stade aux projecteurs", "affiche rock vintage", "noir, rouge, chrome", "sans empattement gras de concert"),
"esprit-goldman": ("une salle de concert vue de la scène avec des mains levées", "illustration chaleureuse", "bleu, orange, blanc", "sans empattement humaniste"),
"esprit-tiersen": ("un piano droit, un accordéon et un toit de Paris", "illustration poétique à l'aquarelle", "vert d'eau, beige, rose pâle", "serif fin manuscrit"),
"blues-vocal": ("un chanteur de blues et un micro sous un lampadaire", "gravure sépia contrastée", "sépia, bleu nuit, rouge", "lettres de pochette vintage"),
"blues-instrumental": ("une guitare slide posée sur une route du Delta", "photographie sépia granuleuse", "sépia, brun, bleu usé", "lettres de pochette vintage"),
"esprit-madness": ("des danseurs en chapeau et costume au motif damier", "graphisme two-tone rieur", "noir, blanc, rouge, jaune", "sans empattement two-tone ludique"),
"esprit-lapointe": ("un chanteur moustachu, des jeux de mots dessinés et une scène de cabaret", "dessin humoristique de presse", "jaune, rouge, bleu", "script fantaisiste rond"),
"esprit-tri-yann": ("un phare, la mer, un triskèle et des voiles de Bretagne", "gravure bretonne colorée", "bleu, blanc, noir, vert", "serif celtique"),
"esprit-vangelis": ("un grand synthétiseur analogique devant un lever de soleil sur l'Acropole", "peinture cinématographique", "or, bleu profond, blanc", "serif gravé de cinéma"),
}

HERE = Path(__file__).resolve().parent.parent
charte = {k: {"sujet": s, "technique": t, "palette": p, "typographie": f} for k, (s, t, p, f) in D.items()}
(HERE / "covers_charte.json").write_text(json.dumps(charte, indent=2, ensure_ascii=False), encoding="utf-8")
ids = {p["id"] for p in json.load(open(HERE / "playlists.json", encoding="utf-8"))} - {"jingles", "jingles-voix"}
print(len(charte), "manquants:", sorted(ids - set(charte)), "en trop:", sorted(set(charte) - ids))
